# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:  
  build_java:
    docker:
      - image: gradle:jdk11

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run: gradle dependencies

      - run: 
          name: Unit tests
          command: gradle test

      - run: 
          name: Gradle build
          command:
            mkdir -p /tmp/libs            
            gradle clean build
            cp ./libs/boilerplate-0.1.0-SNAPSHOT.jar /tmp/libs
  build_docker:
    docker:
      - image: docker:19.03.5

    steps:
    - checkout

    - run:
        name: Docker build
        command:
          cp /tmp/libs/boilerplate-0.1.0-SNAPSHOT.jar ./libs/
          docker build . -t boilerplate
          
workflows:
  version: 2
  boilerplate:
    jobs:
    - build_java
    - build_docker:
          requires:
              - build_java




