spring:
    application:
        name: ${APPLICATION_NAME:boilerplate}
    mvc:
        converters:
            preferred-json-mapper: gson            
server:
    address: ${HOST:0.0.0.0}
    port: ${PORT:8080}
